CREATE TABLE STATION (
    ID SERIAL NOT NULL,
    CITY TEXT NOT NULL,
    CONSTRAINT STATION_PKEY PRIMARY KEY (ID)
);

CREATE TABLE BUS (
    ID SERIAL NOT NULL,
    TYPE TEXT NOT NULL,
    CONSTRAINT BUS_PKEY PRIMARY KEY (ID)
);

CREATE TABLE ROUTE (
    ID SERIAL NOT NULL,
    PICKUP INT NOT NULL,
    DESTINATION INT NOT NULL,
    DISTANCE INT NOT NULL,
    CONSTRAINT ROUTE_PKEY PRIMARY KEY (ID),
    UNIQUE(PICKUP, DESTINATION, DISTANCE),
    CONSTRAINT ROUTE_PICKUP_FK FOREIGN KEY(PICKUP) REFERENCES STATION(ID),
    CONSTRAINT ROUTE_DESTINATION_FK FOREIGN KEY(DESTINATION) REFERENCES STATION(ID)
);

CREATE TABLE TRIP (
    ID SERIAL NOT NULL,
    BUS_ID INT NOT NULL,
    ROUTE_ID INT NOT NULL,
    DATE TEXT NOT NULL,
    CONSTRAINT TRIP_PKEY PRIMARY KEY (ID),
    UNIQUE(ROUTE_ID, BUS_ID, DATE),
    CONSTRAINT TRIP_BUS_ID_FK FOREIGN KEY(BUS_ID) REFERENCES BUS(ID),
    CONSTRAINT TRIP_ROUTE_ID_FK FOREIGN KEY(ROUTE_ID) REFERENCES ROUTE(ID)
);

CREATE TABLE SEAT (
    ID TEXT NOT NULL,
    CONSTRAINT SEAT_PKEY PRIMARY KEY (ID)
);

CREATE TABLE RESERVATION (
    ID TEXT NOT NULL,
    TRIP_ID INT NOT NULL,
    SEAT_ID TEXT NOT NULL,
    EMAIL TEXT NOT NULL,
    DISCOUNT BOOL NOT NULL DEFAULT FALSE,
    RESERVATIONTIME TEXT NOT NULL,
    CONFIRMED BOOL NOT NULL DEFAULT FALSE,
    CONSTRAINT RESERVATION_PKEY PRIMARY KEY (ID),
    CONSTRAINT RESERVATION_TRIP_FK FOREIGN KEY(TRIP_ID) REFERENCES TRIP(ID),
    CONSTRAINT RESERVATION_SEAT_FK FOREIGN KEY(SEAT_ID) REFERENCES SEAT(ID)
);

INSERT INTO
    STATION(CITY)
VALUES
    ('Cairo'),
    ('Alexandria'),
    ('Aswan');

INSERT INTO
    ROUTE(PICKUP, DESTINATION, DISTANCE)
VALUES
    (1, 2, 90),
    (1, 3, 150);

INSERT INTO
    BUS(TYPE)
VALUES
    ('LONG'),
    ('SHORT');

INSERT INTO
    SEAT(ID)
VALUES
    ('A1'),
    ('A2'),
    ('A3'),
    ('A4'),
    ('A5'),
    ('A6'),
    ('A7'),
    ('A8'),
    ('A9'),
    ('A10'),
    ('B1'),
    ('B2'),
    ('B3'),
    ('B4'),
    ('B5'),
    ('B6'),
    ('B7'),
    ('B8'),
    ('B9'),
    ('B10');